# Generated by Django 5.1.7 on 2025-03-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='CustomerInfo',
        ),
    ]
